version: '2'
services:
  publisaiz.java:
    image: azul/zulu-openjdk-alpine:11
    container_name: publisaiz.java
    volumes:
    - "./backend/target:/home/app"
    - "./resources:/resources"
    ports:
    - "80"
    - "443"
    command: java -jar /home/app/publisaiz-0.0.1-SNAPSHOT.jar
    restart: always
    depends_on:
    - publisaiz_postgres
  publisaiz_postgres:
    image: postgres:9.6
    container_name: publisaiz_postgres
    restart: always
    environment:
    - POSTGRES_DB=publisaiz
    - POSTGRES_PASSWORD=!!??rocket123
    - POSTGRES_USER=rocky
    ports:
    - "5432"
    volumes:
    - "./postgres_data:/var/lib/postgresql/data"
    - "./initdb:/docker-entrypoint-initdb.d"
  publisaiz_angular:
    container_name: publisaiz_angular
    image: 'publisaiz_angular'
    build: './frontend'
    ports:
    - "80:80"
    - '443:443'
    restart: always
    depends_on:
    - publisaiz.java
  publisajz_phppgadmin:
    container_name: publisajz_phppgadmin
    image: dockage/phppgadmin
    ports:
    - "99:80"
    environment:
      - PHP_PG_ADMIN_SERVER_HOST=publisaiz_postgres
      - PHP_PG_ADMIN_SERVER_PORT=5432
      - PHP_PG_ADMIN_SERVER_DEFAULT_DB=publisaiz

    