version: '3'
services:
  publisaiz.java:
    image: azul/zulu-openjdk-alpine:11
    container_name: publisaiz.java
    volumes:
    - "./backend/target:/home/app"
    - "./resources:/resources"
    ports:
    - "80"
    command: java -jar /home/app/publisaiz-1.0.0-SNAPSHOT.jar
    restart: always
    depends_on:
    - publisaiz_postgres
  publisaiz_postgres:
    image: postgres:9.6
    container_name: publisaiz_postgres
    restart: always
    environment:
    - POSTGRES_DB=YOUR-POSTGRES-DATABASE
    - POSTGRES_PASSWORD=YOUR-POSTGRES-SCHEMA
    - POSTGRES_USER=YOUR-POSTGRES-USER
    ports:
    - "5432"
    volumes:
    - "./postgres_data:/var/lib/postgresql/data"
    - "./initdb:/docker-entrypoint-initdb.d"
  publisaiz_angular:
    container_name: publisaiz_angular
    # build: '../frontend'
    # image: 'publisaiz_angular'
    image: 'brzezinski/publisaiz:latest'
    ports:
    - "80"
    restart: always
    depends_on:
    - publisaiz.java
  publisaiz_phppgadmin:
    container_name: publisaiz_phppgadmin
    image: dockage/phppgadmin
    ports:
    - "99:80"
    environment:
      - PHP_PG_ADMIN_SERVER_HOST=publisaiz_postgres
      - PHP_PG_ADMIN_SERVER_PORT=5432
      - PHP_PG_ADMIN_SERVER_DEFAULT_DB=publisaiz
  nginx:
    container_name: publisaiz_reverse
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./nginx-certbot-master/data/nginx:/etc/nginx/conf.d
      - ./nginx-certbot-master/data/certbot/conf:/etc/letsencrypt
      - ./nginx-certbot-master/data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    container_name: publisaiz_certbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./nginx-certbot-master/data/certbot/conf:/etc/letsencrypt
      - ./nginx-certbot-master/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
