version: '3'
services:
  publisaiz.java:
    container_name: publisaiz.java
    image: azul/zulu-openjdk-alpine:11
    volumes:
    - "../backend/target:/home/app"
    - "../resources:/resources"
    ports:
    - "8080:80"
    - "8000:8000"
    command: java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n -jar /home/app/publisaiz-1.0.0-SNAPSHOT.jar
    restart: always
    depends_on:
    - publisaiz_postgres
  publisaiz_postgres:
    container_name: publisaiz_postgres
    image: postgres:9.6
    restart: always
    environment:
    - POSTGRES_DB=YOUR-POSTGRES-DATABASE
    - POSTGRES_PASSWORD=YOUR-POSTGRES-PASSWORD
    - POSTGRES_USER=YOUR-POSTGRES-USER
    ports:
    - "5432:5432"
    volumes:
    - "../postgres_data:/var/lib/postgresql/data"
    - "../initdb:/docker-entrypoint-initdb.d"
  publisaiz_angular:
    container_name: publisaiz_angular
    image: 'publisaiz_angular'
    build: '../frontend'
    ports:
    - "80:80"
    restart: always
    depends_on:
    - publisaiz.java
  publisaiz_phppgadmin:
    container_name: publisaiz_phppgadmin
    image: dockage/phppgadmin
    ports:
    - "99:80"
    environment:
      - PHP_PG_ADMIN_SERVER_HOST=publisaiz_postgres
      - PHP_PG_ADMIN_SERVER_PORT=5432
      - PHP_PG_ADMIN_SERVER_DEFAULT_DB=publisaiz
      
    
